language: node_js
sudo: false
node_js:
    - 0.12
    - 5.1.0
env:
  - COVERALLS=1
git:
  depth: 10
before_install:
  - 'npm config set loglevel error'
before_script:
  - sleep 10
after_success:
  - 'npm run coveralls'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
